services:
  psl:
    build: .
    image: psl:latest
    container_name: psl
    environment:
      - HF_HOME=/workspace/data/external/hf_cache
    volumes:
      - ./:/workspace
    tty: true
    stdin_open: true
